---
- name: Deploy cronos mainnet full node
  hosts:
    - matic
  become: true
  vars:
    cronos_home: "{{ ansible_env.HOME }}/.cronos"
    cronos_binary_URL: https://github.com/crypto-org-chain/cronos/releases/download/v0.6.1/cronos_0.6.1_Linux_x86_64.tar.gz
    work_dir: "{{ ansible_env.HOME }}/work/cronos"
    tendermint_rpc_port: 36657
    eth_rpc_port: 9545
    eth_ws_port: 9546
    prometheus_port: 36660
    pip_install_packages:
      - name: docker
  tasks:
    - include: reset.yml
    - include: cronos.yml
  roles:
    - geerlingguy.docker
    # geerlingguy.pipはapt updateしてからでないとFailするので先に別のRoleを読み込んでおく
    - geerlingguy.pip

